name: Generate Snake

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
        uses: actions/checkout@main
        
      - name: Generate
        uses: Platane/snk@main
        
        with:
          github_user_name: lli289
          outputs: 
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.svg
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
